export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_VIDEO = 'FETCH_VIDEO';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CREDITS = 'FETCH_CREDITS';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const RESET_ALL_MOVIES = 'RESET_ALL_MOVIES';
export const RESET_CURRENT_MOVIE = 'RESET_CURRENT_MOVIE';

export const API_KEY = `?api_key=e72a523c89eb32aacfe939b60152e8be`;